language: php
php:
  - 5.3
  - 5.4
script: ./build/build.sh
before_script:
  - mysql -e 'create database Grabagame;'
  - ./deployment/project-setup.sh
branches:
  only:
    - develop
notifications:
  email:
    - chrismckinnel@gmail.com