Grabagame\Bundle\Entity\Booking:
    type: entity
    repositoryClass: Grabagame\Bundle\Repository\BookingRepository
    table: Booking
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        time:
            type: datetime
    manyToOne:
        court:
            targetEntity: Court
            inversedBy: bookings
        user:
            targetEntity: User
            inversedBy: bookings