home:
    pattern:  /
    defaults: { _controller: GrabagameBookingBundle:Booking:index }

add_club:
    pattern:  /add-club/
    defaults: { _controller: Grabagame\BookingBundle\Controller\Admin\ClubController::addClubAction }

submit_add_club:
    pattern:  /submit-add-club/
    defaults: { _controller: Grabagame\BookingBundle\Controller\Admin\ClubController::submitAddClubAction }
