home:
    pattern:  /
    defaults: { _controller: GrabagameBookingBundle:Booking:index }

booking:
    pattern:  /booking/
    defaults: { _controller: GrabagameBookingBundle:Booking:renderBookingTable }

makeBooking:
    pattern:  /make-booking/{courtNumber}/{startTime}/
    defaults: { _controller: GrabagameBookingBundle:Booking:makeBooking }

submitMakeBooking:
    pattern:  /submit-make-booking/
    defaults: { _controller: GrabagameBookingBundle:Booking:submitMakeBooking }

add_club:
    pattern:  /add-club/
    defaults: { _controller: Grabagame\BookingBundle\Controller\Admin\ClubController::addClubAction }

submit_add_club:
    pattern:  /submit-add-club/
    defaults: { _controller: Grabagame\BookingBundle\Controller\Admin\ClubController::submitAddClubAction }
