Grabagame\BookingBundle\Entity\Booking:
    type: entity
    repositoryClass: Grabagame\BookingBundle\Repository\BookingRepository
    table: Booking
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        startTime:
            type: datetime
        slots:
            type: integer
    manyToOne:
        court:
            targetEntity: Court
            inversedBy: bookings
        member:
            targetEntity: Member
            inversedBy: bookings