Grabagame\Bundle\Entity\Court:
    type: entity
    repositoryClass: Grabagame\Bundle\Repository\CourtRepository
    table: Court
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        number:
            type: integer
    oneToMany:
        bookings:
            targetEntity: Booking
            mappedBy: court
    manyToOne:
        club:
            targetEntity: Club
            inversedBy: courts