home:
    pattern:  /
    defaults: { _controller: GrabagameBookingBundle:Booking:index }

booking:
    pattern:  /booking/
    defaults: { _controller: GrabagameBookingBundle:Booking:renderBookingTable }
