parameters:
    base_logging_url: /var/www/grabagame/app/logs

services:
    service.loggerAware:
        class: Grabagame\BookingBundle\Service\LoggerAware
    
    service.booking:
        class: Grabagame\BookingBundle\Service\BookingService
        parent: service.loggerAware
        calls:
            - [ setDoctrine, [@doctrine] ]
            - [ setLogger, [@logger, %base_logging_url%, 'BookingService'] ]
